"""
Dados mínimos para seed da tabela knowledge_chunks.
Um chunk por área (Fundamentos Narrativos) + um genérico de metodologia.
Embeddings são gerados pelo script seed_knowledge_chunks.py.
"""

CHUNKS = [
    {
        "chapter": "Saúde Física",
        "section": "Fundamentos Narrativos",
        "content": "A Saúde Física refere-se à manutenção da constituição física e disposição corporal necessária para executar as tarefas da jornada. Na metodologia, o corpo é o principal canal das mensagens e o codificador singular da nova identidade. Sinais de conflito M1: exaustão crônica, falta de domínio sobre hábitos biológicos, incongruência entre imagem física e identidade pretendida.",
        "motor_motivacional": ["Necessidade", "Desejo"],
        "estagio_jornada": ["Germinar", "Desenvolver"],
        "tipo_crise": ["Execução"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["exaustão", "procrastinação"],
        "tom_emocional": "apatia",
    },
    {
        "chapter": "Saúde Mental",
        "section": "Fundamentos Narrativos",
        "content": "Foca no equilíbrio das funções cognitivas e na gestão das emoções para evitar sabotagens internas. É o campo onde se aplica a TCC para reestruturar a velha narrativa. Sinais de conflito M1: narrativa interna caótica, bloqueios por vergonha do passado, ansiedade por falta de linearidade entre passado e futuro.",
        "motor_motivacional": ["Necessidade", "Valor"],
        "estagio_jornada": ["Germinar", "Enraizar"],
        "tipo_crise": ["Identidade", "Sentido"],
        "ponto_entrada": "Simbólico",
        "sintomas": ["autossabotagem", "ruminação"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Saúde Espiritual",
        "section": "Fundamentos Narrativos",
        "content": "Relaciona-se à força da fé e à convicção interior que impulsionam a manifestação dos propósitos da alma. É a âncora que dá sentido à travessia. Sinais de conflito M1: vazio existencial, crise de indignidade perante a própria grandeza, desconexão com os valores inegociáveis.",
        "motor_motivacional": ["Valor", "Propósito"],
        "estagio_jornada": ["Enraizar", "Florescer"],
        "tipo_crise": ["Sentido"],
        "ponto_entrada": "Simbólico",
        "sintomas": ["vazio", "desconexão"],
        "tom_emocional": "apatia",
    },
    {
        "chapter": "Vida Pessoal",
        "section": "Fundamentos Narrativos",
        "content": "Concentra-se no autoconhecimento, na descoberta da própria essência e na organização dos interesses individuais. É o centro da Luz Total da personagem. Sinais de conflito M1: sensação de estar perdido em narrativas alheias, falta de enredo unificador, vazio por falta de Fantasia Pessoal estimulante.",
        "motor_motivacional": ["Valor", "Desejo"],
        "estagio_jornada": ["Germinar", "Enraizar"],
        "tipo_crise": ["Identidade"],
        "ponto_entrada": "Simbólico",
        "sintomas": ["identidade herdada", "confusão"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Vida Amorosa",
        "section": "Fundamentos Narrativos",
        "content": "Abrange os relacionamentos íntimos e o convívio afetuoso. Busca-se parcerias que nutram a construção do Círculo Narrativo Futuro (CN+). Sinais de conflito M1: vínculos superficiais, incongruência entre valores do parceiro e própria trajetória, medo de se perder ao crescer.",
        "motor_motivacional": ["Necessidade", "Valor"],
        "estagio_jornada": ["Enraizar", "Desenvolver"],
        "tipo_crise": ["Conexão", "Identidade"],
        "ponto_entrada": "Emocional",
        "sintomas": ["autossabotagem afetiva"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Vida Familiar",
        "section": "Fundamentos Narrativos",
        "content": "Trata dos vínculos de parentesco e dos valores morais inicialmente absorvidos. É onde se encontram as Identidades Herdadas que precisam ser ressignificadas. Sinais de conflito M1: conflitos de valores, vergonha da origem, atuar papéis impostos por tradições obsoletas.",
        "motor_motivacional": ["Valor", "Necessidade"],
        "estagio_jornada": ["Germinar", "Enraizar"],
        "tipo_crise": ["Identidade"],
        "ponto_entrada": "Simbólico",
        "sintomas": ["identidade herdada", "vergonha"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Vida Social",
        "section": "Fundamentos Narrativos",
        "content": "Refere-se às interações com a comunidade e à seleção de redes de contato. O crescimento ocorre ao orbitar ambientes nutritivos e pessoas condutoras. Sinais de conflito M1: ambientes estagnados, solidão existencial mesmo rodeado de pessoas, medo do julgamento ou de brilhar em público.",
        "motor_motivacional": ["Desejo", "Propósito"],
        "estagio_jornada": ["Desenvolver", "Florescer"],
        "tipo_crise": ["Conexão"],
        "ponto_entrada": "Emocional",
        "sintomas": ["invisibilidade simbólica", "medo do julgamento"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Vida Profissional",
        "section": "Fundamentos Narrativos",
        "content": "Foca na atuação produtiva, no domínio de competências técnicas e no desenvolvimento da carreira e autoridade (Capital Simbólico). Sinais de conflito M1: atuar papel que não condiz com quem se é, invisibilidade em espaços de poder, procrastinação por falta de clareza sobre o próximo clímax profissional.",
        "motor_motivacional": ["Desejo", "Valor"],
        "estagio_jornada": ["Desenvolver", "Frutificar"],
        "tipo_crise": ["Execução", "Transformação"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["síndrome do impostor", "procrastinação"],
        "tom_emocional": "urgência",
    },
    {
        "chapter": "Finanças",
        "section": "Fundamentos Narrativos",
        "content": "Envolve a gestão do capital econômico e recursos materiais para sustentar a estrutura de vida e o Círculo Narrativo. Sinais de conflito M1: ansiedade por desorganização material, crenças limitantes de escassez herdadas, falta de recursos para materializar a visão MX.",
        "motor_motivacional": ["Necessidade", "Desejo"],
        "estagio_jornada": ["Germinar", "Desenvolver"],
        "tipo_crise": ["Execução"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["ansiedade", "crenças de escassez"],
        "tom_emocional": "urgência",
    },
    {
        "chapter": "Educação",
        "section": "Fundamentos Narrativos",
        "content": "Diz respeito à busca contínua por conhecimento, aprendizagem sistemática e aperfeiçoamento intelectual. É o processo de Modelagem ativa de novos padrões. Sinais de conflito M1: estagnação intelectual, excesso de preparação sem ação (paralisia), dificuldade em transformar informação em habilidade prática.",
        "motor_motivacional": ["Desejo", "Valor"],
        "estagio_jornada": ["Desenvolver", "Florescer"],
        "tipo_crise": ["Execução"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["paralisia decisória"],
        "tom_emocional": "apatia",
    },
    {
        "chapter": "Inovação",
        "section": "Fundamentos Narrativos",
        "content": "Capacidade de criar, pesquisar e desenvolver novas formas de resolver problemas ou expressar a identidade. É a ousadia de testar limites criativos. Sinais de conflito M1: medo de recomeçar, bloqueio criativo por excesso de autocrítica, repetição de ciclos exaustivos sem renovação.",
        "motor_motivacional": ["Desejo", "Propósito"],
        "estagio_jornada": ["Desenvolver", "Frutificar"],
        "tipo_crise": ["Transformação"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["medo de recomeçar", "bloqueio criativo"],
        "tom_emocional": "vergonha",
    },
    {
        "chapter": "Lazer",
        "section": "Fundamentos Narrativos",
        "content": "Compreende as atividades de entretenimento e o uso do tempo livre para recuperação de energia e prazer. Serve como ritual de descompressão necessário para manter a constância. Sinais de conflito M1: culpa por descansar, lazer viciado que drena em vez de nutrir, ausência de pausas para celebrar microvitórias.",
        "motor_motivacional": ["Necessidade", "Valor"],
        "estagio_jornada": ["Desenvolver", "Florescer"],
        "tipo_crise": ["Execução"],
        "ponto_entrada": "Comportamental",
        "sintomas": ["culpa", "exaustão"],
        "tom_emocional": "urgência",
    },
    {
        "chapter": "Metodologia",
        "section": "Fases da Jornada",
        "content": "A jornada de transformação narrativa passa por seis fases: Germinar (reconhecer o motor), Enraizar (modelar valores), Desenvolver (assumir ritos), Florescer (reforçar voz), Frutificar (consolidar resultados), Realizar (estabelecer legado). Os quatro motores motivacionais são Necessidade (alívio da dor), Valor (coerência), Desejo (conquista), Propósito (impacto).",
        "motor_motivacional": ["Necessidade", "Valor", "Desejo", "Propósito"],
        "estagio_jornada": ["Germinar", "Enraizar", "Desenvolver", "Florescer", "Frutificar", "Realizar"],
        "tipo_crise": ["Identidade", "Sentido", "Execução", "Conexão", "Incongruência", "Transformação"],
        "ponto_entrada": "Simbólico",
        "sintomas": ["autossabotagem", "paralisia decisória", "invisibilidade simbólica"],
        "tom_emocional": "vergonha",
    },
]
